BASE:
 language: "en-US"

AIN:
 frame_length: 0.005 # sec
 sample_rate: 16000 # Hz
 sample_width: 2 # Bytes
 num_channel: 1

ASR:
 buff_size: 10
 json_key: <enter your json path>
 chunk_size: 20
 sample_rate: 16000 # Hz
 tagger: None

VAP:
 model_filename: ../models/vap/sw2japanese_public0.ckpt
 buffer_length: 25 # ms
 threshold: 0.75

DIALOGUE:
 history_length: 5
 response_generation_timeout: 3.0 # sec
 response_generation_interval: 1
 spacer: ' '
 backchannels: ['Oh', 'Uh', 'Yeah']
 max_silence_time: 5.0 # sec

ChatGPT:
 api_key: <enter your API key>
 max_tokens: 128
 max_message_num_in_context: 4
 response_generation_model: "gpt-4o-mini" # "gpt-4-1106-preview"
 text_vap_model: "gpt-4o-mini"
 prompts:
  BC: prompts/text_vap.txt
  RESP: prompts/response.txt
  INTENT: prompts/time_out.txt
 split_pattern: "[,.?!]"

TEXT_VAP:
 max_verbal_backchannel_num: 2
 max_nonverbal_backchannel_num: 1
 mix_text_vap_threshold: 6
 text_vap_interval: 3
 spacer: ' '

Intention:
 max_silence_time: 5 # sec
 max_timeout_num: 3
 block_time: 10 # sec

TTS:
 engine_name: TTS
 model_name: tts_models/en/ljspeech/vits
 frame_length: 0.05 # Sec
 send_interval: 0.04 # Sec
 org_sample_rate: 22050 # Hz
 dst_sample_rate: 16000 # Hz
 scale_factor: 32768.0
 sample_width: 2 # Bytes

AOUT:
 frame_length: 0.05 # Sec
 sample_rate: 16000 # Hz
 sample_width: 2 # Bytes
 num_channel: 1